from datetime import datetime
from uuid import UUID

import pytest

from compactref import (
    MAX_ATTEMPT,
    SourceIdentifier,
    collision_probability,
    expected_collisions,
    generate_reference,
    max_references,
)


FIXED_DATETIME = datetime(2026, 7, 10, 12, 30)
FIXED_ULID = "01J2H8NQPG6B5X8KGN97SX3R5C"
FIXED_UUID = UUID("b37fd04a-10b7-47b8-a5fe-76e3e615f441")


def test_generates_numeric_reference_from_ulid() -> None:
    reference = generate_reference(
        FIXED_ULID,
        generated_at=FIXED_DATETIME,
    )

    assert reference.startswith("20260710")
    assert len(reference) == 14
    assert reference.isdigit()


def test_same_input_produces_same_reference() -> None:
    first_reference = generate_reference(
        FIXED_ULID,
        generated_at=FIXED_DATETIME,
    )

    second_reference = generate_reference(
        FIXED_ULID,
        generated_at=FIXED_DATETIME,
    )

    assert first_reference == second_reference


def test_different_sources_usually_produce_different_references() -> None:
    first_reference = generate_reference(
        "01J2H8NQPG6B5X8KGN97SX3R5C",
        generated_at=FIXED_DATETIME,
    )

    second_reference = generate_reference(
        "01J2H8NQPG6B5X8KGN97SX3R5D",
        generated_at=FIXED_DATETIME,
    )

    assert first_reference != second_reference


def test_accepts_uuid() -> None:
    reference = generate_reference(
        FIXED_UUID,
        generated_at=FIXED_DATETIME,
    )

    assert reference.startswith("20260710")
    assert reference.isdigit()


def test_accepts_bytes() -> None:
    reference = generate_reference(
        b"internal-record-123",
        generated_at=FIXED_DATETIME,
    )

    assert reference.startswith("20260710")


def test_accepts_integer() -> None:
    reference = generate_reference(
        123456789,
        generated_at=FIXED_DATETIME,
    )

    assert reference.startswith("20260710")


def test_supports_prefix_and_separator() -> None:
    reference = generate_reference(
        FIXED_ULID,
        generated_at=FIXED_DATETIME,
        prefix="INC",
        separator="-",
    )

    assert reference.startswith("INC-20260710-")
    assert len(reference.split("-")[-1]) == 6


def test_supports_custom_suffix_length() -> None:
    reference = generate_reference(
        FIXED_ULID,
        generated_at=FIXED_DATETIME,
        suffix_length=8,
    )

    assert reference.startswith("20260710")
    assert len(reference) == 16


def test_supports_custom_date_format() -> None:
    reference = generate_reference(
        FIXED_ULID,
        generated_at=FIXED_DATETIME,
        date_format="%y%m%d",
    )

    assert reference.startswith("260710")
    assert len(reference) == 12


@pytest.mark.parametrize("suffix_length", [0, -1, -10])
def test_rejects_invalid_suffix_length(
    suffix_length: int,
) -> None:
    with pytest.raises(
        ValueError,
        match="suffix_length must be greater than zero",
    ):
        generate_reference(
            FIXED_ULID,
            suffix_length=suffix_length,
        )


@pytest.mark.parametrize("source", ["", " ", b""])
def test_rejects_empty_source(
    source: str | bytes,
) -> None:
    with pytest.raises(
        ValueError,
        match="source must not be empty",
    ):
        generate_reference(source)


def test_rejects_negative_integer() -> None:
    with pytest.raises(
        ValueError,
        match="integer source must not be negative",
    ):
        generate_reference(-1)


def test_rejects_unsupported_source_type() -> None:
    with pytest.raises(
        TypeError,
        match=(
            "source must be a string, bytes, non-negative integer, or UUID"
        ),
    ):
        generate_reference(["unsupported"])  # type: ignore[arg-type]


# References generated by 0.1.0, before the attempt argument existed.
# Anything stored by a caller on that version has to keep recomputing to
# the same string, so these are pinned rather than derived.
@pytest.mark.parametrize(
    ("source", "expected"),
    [
        ("01J2H8NQPG6B5X8KGN97SX3R5C", "20260710385177"),
        (UUID("b37fd04a-10b7-47b8-a5fe-76e3e615f441"), "20260710893023"),
        (b"internal-record-123", "20260710016594"),
        (123456789, "20260710284854"),
    ],
)
def test_default_attempt_reproduces_pre_attempt_references(
    source: SourceIdentifier,
    expected: str,
) -> None:
    assert generate_reference(source, generated_at=FIXED_DATETIME) == expected


def test_attempt_zero_is_the_default() -> None:
    default = generate_reference(FIXED_ULID, generated_at=FIXED_DATETIME)
    explicit = generate_reference(
        FIXED_ULID,
        generated_at=FIXED_DATETIME,
        attempt=0,
    )

    assert default == explicit


def test_attempt_changes_the_reference() -> None:
    first = generate_reference(FIXED_ULID, generated_at=FIXED_DATETIME)
    second = generate_reference(
        FIXED_ULID,
        generated_at=FIXED_DATETIME,
        attempt=1,
    )

    assert first != second


def test_attempt_is_deterministic() -> None:
    first = generate_reference(
        FIXED_ULID,
        generated_at=FIXED_DATETIME,
        attempt=7,
    )
    second = generate_reference(
        FIXED_ULID,
        generated_at=FIXED_DATETIME,
        attempt=7,
    )

    assert first == second


def test_attempt_keeps_the_prefix_and_date() -> None:
    reference = generate_reference(
        FIXED_ULID,
        generated_at=FIXED_DATETIME,
        prefix="INC",
        separator="-",
        attempt=3,
    )

    assert reference.startswith("INC-20260710-")
    assert len(reference.split("-")[-1]) == 6


def test_successive_attempts_are_distinct() -> None:
    references = {
        generate_reference(
            FIXED_ULID,
            generated_at=FIXED_DATETIME,
            attempt=attempt,
        )
        for attempt in range(50)
    }

    assert len(references) == 50


def test_attempt_is_not_the_same_as_a_suffixed_source() -> None:
    # The attempt is salted, not appended. If it were appended, these two
    # would agree, and the collision fix would introduce a collision.
    salted = generate_reference(
        "abc",
        generated_at=FIXED_DATETIME,
        attempt=1,
    )
    appended = generate_reference(
        "abc1",
        generated_at=FIXED_DATETIME,
    )

    assert salted != appended


def test_accepts_the_largest_attempt() -> None:
    reference = generate_reference(
        FIXED_ULID,
        generated_at=FIXED_DATETIME,
        attempt=MAX_ATTEMPT,
    )

    assert reference.startswith("20260710")


@pytest.mark.parametrize("attempt", [-1, -10])
def test_rejects_negative_attempt(attempt: int) -> None:
    with pytest.raises(
        ValueError,
        match="attempt must not be negative",
    ):
        generate_reference(FIXED_ULID, attempt=attempt)


def test_rejects_attempt_above_the_maximum() -> None:
    with pytest.raises(
        ValueError,
        match="attempt must not be greater than",
    ):
        generate_reference(FIXED_ULID, attempt=MAX_ATTEMPT + 1)


@pytest.mark.parametrize("reference_count", [0, 1])
def test_collision_probability_is_zero_below_two_references(
    reference_count: int,
) -> None:
    assert collision_probability(reference_count, suffix_length=6) == 0.0


def test_collision_probability_increases_with_reference_count() -> None:
    fewer = collision_probability(50, suffix_length=4)
    more = collision_probability(120, suffix_length=4)

    assert 0.0 < fewer < more < 1.0


def test_collision_probability_decreases_with_longer_suffix() -> None:
    short_suffix = collision_probability(120, suffix_length=4)
    long_suffix = collision_probability(120, suffix_length=6)

    assert long_suffix < short_suffix


def test_collision_probability_matches_birthday_approximation() -> None:
    # 1 - exp(-n*(n-1) / (2 * 10**length)) for n=100, length=4
    probability = collision_probability(100, suffix_length=4)

    assert probability == pytest.approx(0.3904, abs=1e-4)


@pytest.mark.parametrize("suffix_length", [0, -1])
def test_collision_probability_rejects_invalid_suffix_length(
    suffix_length: int,
) -> None:
    with pytest.raises(
        ValueError,
        match="suffix_length must be greater than zero",
    ):
        collision_probability(10, suffix_length=suffix_length)


def test_collision_probability_rejects_negative_reference_count() -> None:
    with pytest.raises(
        ValueError,
        match="reference_count must not be negative",
    ):
        collision_probability(-1, suffix_length=6)


@pytest.mark.parametrize("reference_count", [0, 1])
def test_expected_collisions_is_zero_below_two_references(
    reference_count: int,
) -> None:
    assert expected_collisions(reference_count, suffix_length=6) == 0.0


def test_expected_collisions_matches_the_pair_count() -> None:
    # 300 * 299 / (2 * 10**4)
    assert expected_collisions(300, suffix_length=4) == pytest.approx(4.485)


def test_expected_collisions_grows_with_reference_count() -> None:
    fewer = expected_collisions(50, suffix_length=4)
    more = expected_collisions(120, suffix_length=4)

    assert 0.0 < fewer < more


def test_expected_collisions_decreases_with_longer_suffix() -> None:
    short_suffix = expected_collisions(300, suffix_length=4)
    long_suffix = expected_collisions(300, suffix_length=6)

    assert long_suffix < short_suffix


def test_expected_collisions_keeps_counting_past_certainty() -> None:
    # The point of the function: collision_probability saturates at
    # "certain" and stops separating a crowded format from a hopeless
    # one. The expected count still does.
    crowded = collision_probability(2_000, suffix_length=3)
    hopeless = collision_probability(20_000, suffix_length=3)

    assert crowded == pytest.approx(1.0)
    assert hopeless == pytest.approx(1.0)

    assert expected_collisions(20_000, suffix_length=3) > (
        expected_collisions(2_000, suffix_length=3)
    )


@pytest.mark.parametrize("suffix_length", [0, -1])
def test_expected_collisions_rejects_invalid_suffix_length(
    suffix_length: int,
) -> None:
    with pytest.raises(
        ValueError,
        match="suffix_length must be greater than zero",
    ):
        expected_collisions(10, suffix_length=suffix_length)


def test_expected_collisions_rejects_negative_reference_count() -> None:
    with pytest.raises(
        ValueError,
        match="reference_count must not be negative",
    ):
        expected_collisions(-1, suffix_length=6)


def test_max_references_grows_with_suffix_length() -> None:
    assert max_references(4) < max_references(6) < max_references(8)


def test_max_references_grows_with_allowed_probability() -> None:
    strict = max_references(6, max_probability=0.01)
    lenient = max_references(6, max_probability=0.50)

    assert strict < lenient


def test_max_references_stays_within_target_probability() -> None:
    limit = max_references(6, max_probability=0.01)

    assert collision_probability(limit, suffix_length=6) <= 0.01
    assert collision_probability(limit + 1, suffix_length=6) > 0.01


@pytest.mark.parametrize("suffix_length", [0, -1])
def test_max_references_rejects_invalid_suffix_length(
    suffix_length: int,
) -> None:
    with pytest.raises(
        ValueError,
        match="suffix_length must be greater than zero",
    ):
        max_references(suffix_length)


@pytest.mark.parametrize("max_probability", [0.0, 1.0, -0.1, 1.5])
def test_max_references_rejects_invalid_probability(
    max_probability: float,
) -> None:
    with pytest.raises(
        ValueError,
        match="max_probability must be between 0 and 1",
    ):
        max_references(6, max_probability=max_probability)
